# Generated by Django 2.0.4 on 2018-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('mod_date', models.DateTimeField(verbose_name='date modified')),
                ('parent_category', models.ManyToManyField(blank=True, related_name='_category_parent_category_+', to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('mod_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
