# Generated by Django 2.0.4 on 2018-06-26 20:56

from django.db import migrations, models
import product.storage


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=product.storage.MyImageStorage(), upload_to=''),
        ),
    ]
