# Generated by Django 2.0.4 on 2018-07-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180708_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecUnits',
            new_name='SpecUnit',
        ),
    ]
