# Generated by Django 2.0.4 on 2018-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180506_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(blank=True, related_name='_category_parent_category_+', to='product.Category'),
        ),
    ]
