# Generated by Django 2.0.4 on 2018-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180506_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mod_date',
            field=models.DateTimeField(verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mod_date',
            field=models.DateTimeField(verbose_name='date modified'),
        ),
    ]
