# Generated by Django 2.0.4 on 2018-06-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180604_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=123, max_length=80),
            preserve_default=False,
        ),
    ]
