# Generated by Django 2.0.4 on 2018-06-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20180604_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
