# Generated by Django 2.0.4 on 2018-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
