# Generated by Django 2.0.4 on 2018-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20180623_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
